change deploy to create .env for docker-compose

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -43,11 +43,18 @@ function deploy.__initGlobals()
     export CONFIG_DIR="${base_dir}"
     readonly CONFIG_DIR
 
+    # verify docker-compose.yml in 'config' dir
+    export CONFIG_YAML="${CONFIG_DIR}/docker-compose.yml"
+    readonly CONFIG_YAML
+    [ -e "$CONFIG_YAML" ] || trap.die "Invalid configuration - no $CONFIG_YAML"
+
+
     export DEPLOY_YAML="${CONFIG_DIR}/deploy.yml"
     [ -e "$DEPLOY_YAML" ] || trap.die "Unable to locate deploy configuration file: $DEPLOY_YAML"
     readonly DEPLOY_YAML
 
     local deploy_json="$(lib.yamlToJson "$DEPLOY_YAML")"
+
 
     # verify our basic setup is good
     export CONTAINER_OS="$(jq --compact-output --monochrome-output --raw-output 'try .container_os' <<< "$deploy_json" ||:)"
@@ -57,12 +64,6 @@ function deploy.__initGlobals()
     export WORKSPACE_DIR="$(deploy.workspace "$base_dir")"
     readonly WORKSPACE_DIR
     export WORKSPACE_YAML="${WORKSPACE_DIR}/docker-compose.yml"
-
-    # verify docker-compose.yml in 'config' dir
-    export CONFIG_YAML="${CONFIG_DIR}/docker-compose.yml"
-    readonly CONFIG_YAML
-    [ -e "$CONFIG_YAML" ] || trap.die "Invalid configuration - no $CONFIG_YAML"
-
 
     local -i file_count=0
     if [ -d "$WORKSPACE_DIR" ]; then
@@ -380,9 +381,7 @@ function deploy.down()
     [ "$networkCount" -gt 0 ] || return 1
 
     # need docker-compose.yml to stop/remove running containers
-    mkdir -p "$WORKSPACE_DIR" ||:
-    sudo cp "$CONFIG_YAML" "$WORKSPACE_YAML"
-    sudo  sed -Ei -e 's|(:\?})|:-}|g' "$WORKSPACE_YAML"
+    deploy.fixWorkspaceYaml
 
     term.log 'INFO: bringing down containers to allow "workspace" to be refreshed\n' 'lt_magenta'
     term.log '$docker-compose down --remove-orphans\n' 'grey'
@@ -461,6 +460,14 @@ function deploy.fixupDCLineBeforeRun()
 }
 
 #----------------------------------------------------------------------------------------------
+function deploy.fixWorkspaceYaml()
+{
+    mkdir -p "$WORKSPACE_DIR" ||:
+    [ -f "$WORKSPACE_YAML" ] && rm "$WORKSPACE_YAML"
+    [ -h "$WORKSPACE_YAML" ] || ln -s "$CONFIG_YAML" "$WORKSPACE_YAML"
+}
+
+#----------------------------------------------------------------------------------------------
 # parse all BASH tokens/variables from a file
 function deploy.getTokens() {
   local file="${1:?}"
@@ -473,10 +480,6 @@ function deploy.getTokens() {
 # setup workspace if it does not exist
 function deploy.initialize()
 {
-    # create WORKSPACE_DIR/docker-compose.yml
-    deploy.updateDockerCompose 'createWsYaml'
-
-
     local json="$(lib.yamlToJson "$WORKSPACE_YAML")"
     [ $? -ne 0 ] && trap.die "Failed to parse $WORKSPACE_YAML"
     local -ri num_secrets=$(jq --compact-output --monochrome-output '.services[]|select(has("secrets"))|.secrets[]' <<< "$json" | wc -l)
@@ -485,7 +488,7 @@ function deploy.initialize()
 
     # create the folders which are mounted by containers (defined in docker-compose volumes)
     local -A service_tasks=()
-    for service_name in $(lib.yamlToJson "$WORKSPACE_YAML" | jq --compact-output --monochrome-output --raw-output '.services|keys[]?'); do
+    for service_name in $(jq --compact-output --monochrome-output --raw-output '.services|keys[]?' <<< "$json"); do
 
         # look for individual service tasks (to run later)
         local initFunction="${CONFIG_DIR}/${service_name}.setup"
@@ -502,8 +505,9 @@ function deploy.initialize()
         "${service_tasks[$task]}" ||:
     done
 
+
     # update secret references (cannot apply these with other docker-compose.yml updates)
-    [ "$num_secrets" -eq 0 ] || deploy.updateSecretRefs "$WORKSPACE_YAML"
+    [ "$num_secrets" -eq 0 ] || deploy.updateSecretRefs "$CONFIG_YAML"
 }
 
 #----------------------------------------------------------------------------------------------
@@ -537,7 +541,7 @@ function deploy.main()
     deploy.__initGlobals "${OPTS['base']}" "${OPTS['latest']:-}"
 
     [ -z "${OPTS['clean']:-}" ] || deploy.clean
-    mkdir -p "$WORKSPACE_DIR" ||:
+    deploy.fixWorkspaceYaml
 
 
     if [ "${OPTS['init']:-}" ]; then
@@ -744,7 +748,6 @@ function deploy.restartContainers()
     if [ "${latest:-}" = 'HEAD' ]; then
         echo
         # Updating reference docker-compose.yml
-        deploy.updateDockerCompose 'updateWsYaml'
         deploy.updateDockerCompose 'updateCfgYaml'
     fi
     return 0
@@ -771,21 +774,6 @@ function deploy.updateDockerCompose()
 
     # setup the conditions to control how docker.compose gets updated
     case "$mode" in
-        createWsYaml)
-            # update docker-compose
-            src_yaml="$CONFIG_YAML"
-            dst_yaml="$WORKSPACE_YAML"
-            process='deploy.fixupDCLineBeforeRun'
-            ;;
-
-        updateWsYaml)
-            src_yaml="$CONFIG_YAML"
-            dst_yaml="$WORKSPACE_YAML"
-            process='deploy.fixupDCLineAfterRun'
-            json=$(lib.yamlToJson "$dst_yaml")
-            args=( '.newline' )
-            ;;
-
         updateCfgYaml)
             src_yaml="$CONFIG_YAML"
             dst_yaml="$CONFIG_YAML"
@@ -849,21 +837,30 @@ function deploy.updateDockerCompose()
     ) > "$tmp_file"
     [ $? -ne 0 ] && trap.die "Failed to process file: $dst_yaml"
 
+    deploy.updateFile "$tmp_file" "$src_yaml"
+}
+
+#----------------------------------------------------------------------------------------------
+function deploy.updateFile()
+{
+    local -r tmp_file=${1:?}
+    local -r org_file=${2:?}
+
     # if there are no changes, delete tmp file
-    if [ "$(lib.fileSha256 "$dst_yaml")" = "$(lib.fileSha256 "$tmp_file")" ]; then
+    if [ "$(lib.fileSha256 "$org_file")" = "$(lib.fileSha256 "$tmp_file")" ]; then
         rm "$tmp_file"
         return 0   # no updates
     fi
 
-    # otherwise rename 'src_yaml' to file.YYYYMMDDhhmmss.bak and rename updated file to 'dst_yaml'
-    # create backup of dstfile before we update it
-    term.log "INFO: updating ${dst_yaml}"'\n' 'white'
-    if [ -f "$dst_yaml" ]; then
-        local backup="${dst_yaml%.*}.$(date +"%Y%m%d%H%M%S").${dst_yaml##*.}.bak"
+    # otherwise rename 'org_file' to ~org_file.YYYYMMDDhhmmss.bak and rename tmp_file to 'org_file'
+    # create backup of org_file before we update it
+    term.log "INFO: updating ${org_file}"'\n' 'white'
+    if [ -f "$org_file" ]; then
+        local backup="${org_file%.*}.$(date +"%Y%m%d%H%M%S").${org_file##*.}.bak"
         backup="$(dirname "$backup")/~$(basename "$backup")"
-        mv "$dst_yaml" "$backup"
+        mv "$org_file" "$backup"
     fi
-    mv "$tmp_file" "$dst_yaml"   # file updated
+    mv "$tmp_file" "$org_file"   # file updated
     return 0
 }
 
@@ -871,14 +868,18 @@ function deploy.updateDockerCompose()
 function deploy.updateSecretRefs()
 {
     local -r dc_yaml=${1:?}
-    sed -i -r -e 's|file:\s+~/|file: '"$(readlink -f ~)"'/|' "$dc_yaml"
+    local tmp_file="${dc_yaml}.tmp"
+    sed -r -e 's|file:\s+~/|file: '"$(readlink -f ~)"'/|' "$dc_yaml" > "$tmp_file"
+
+    deploy.updateFile "$tmp_file" "$dc_yaml"
 }
 
 #----------------------------------------------------------------------------------------------
 function deploy.validateDockerComposeYaml()
 {
     local -r dc_yaml=${1:?}
-    [ $(jq --compact-output --monochrome-output '.services[].ports[]' <<< "$dc_yaml" | sort | wc -l) -eq $(jq --compact-output --monochrome-output '.services[].ports[]' <<< "$dc_yaml"| sort -u) ] || return 1
+    local ports=$(jq --compact-output --monochrome-output '.services[].ports[]' <<< "$dc_yaml")
+    [ $(echo $ports | sort | wc -l) -eq $(echo $ports | sort -u) ] || return 1
 }
 
 #----------------------------------------------------------------------------------------------
@@ -888,20 +889,31 @@ function deploy.verifyEnvironmentForFile()
 
     local var
     local -a unknown=()
+    local -a tokens=()
 
     # scan file for BASH tokens of form: ${TOKEN} or ${TOKEN:-default} or ${TOKEN:?}
     while read -r var; do
         # ignore tokens which have a default value
-        [ $(grep -c '?' <<< "$var") -ne 0 ] || continue
-
-        var="${var%%=*}"                             # extract token
-        [ "${var:-}" ] || continue                   # ignore if null
-        [ -z "${!var:-}" ] && unknown+=( "$var" )    # add to 'unknown' unless TOKEN exists in our ENV
+        if [ $(grep -c '?' <<< "$var") -ne 0 ]; then
+            var="${var%%=*}"                             # extract token
+            [ "${var:-}" ] || continue                   # ignore if null
+            if [ -z "${!var:-}" ]; then
+                unknown+=( "$var" )    # add to 'unknown' unless TOKEN exists in our ENV
+                continue
+            fi
+            var="${var}=${!var}"
+        fi
+        tokens+=( "$var" )
     done < <(deploy.getTokens "$file" | grep -Ev 'CONTAINER_TAG|DEV_TEAM' | sort -u ||: )
 
     if [ ${#unknown[*]} -gt 0 ]; then
         trap.die 'The following environment variables are undefined:'$(printf '\n    %s' "${unknown[@]}")
     fi
+    
+    local org_file="${WORKSPACE_DIR}/.env"
+    local tmp_file="${WORKSPACE_DIR}/.env.tmp"
+    printf '%s\n' "${tokens[@]}" > "$tmp_file"
+    deploy.updateFile "$tmp_file" "$org_file"
 }
 
 #----------------------------------------------------------------------------------------------
