fixes to docker-utilities

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -90,22 +90,22 @@ function deploy.__initGlobals()
     : ${CFG_USER:=${USERNAME:-}}
     : ${CFG_USER:=${USER:-}}
     CFG_USER="${CFG_USER%@*}"
-    readonly CFG_USER
-
     export CFG_NAME="${CFG_NAME:-$(git.userName)}"
-    readonly CFG_NAME
-
     export CFG_EMAIL="${CFG_EMAIL:-$(git.userEmail)}"
-    readonly CFG_EMAIL
 
-    : ${CFG_USER:?"CFG_USER has not been configured. Please ensure that your 'git' configuration is valid"}	
-    : ${CFG_NAME:?"CFG_NAME has not been configured. Please ensure that your 'git' configuration is valid"}	
-    : ${CFG_EMAIL:?"CFG_EMAIL has not been configured. Please ensure that your 'git' configuration is valid"}	
+    [ "${CFG_USER:-}" ] || term.elog 'CFG_USER has not been configured.\n' 'yellow'
+    [ "${CFG_NAME:-}" ] || term.elog 'CFG_NAME has not been configured.\n'  'yellow'
+    [ "${CFG_EMAIL:-}" ] || term.elog 'CFG_EMAIL has not been configured.\n' 'yellow'
+    [ "${CFG_USER:-}" ] && [ "${CFG_NAME:-}" ] && [ "${CFG_EMAIL:-}" ] || deploy.configSettingsHelp
+    # verify we have the mandatory env variables defined
+    [ "${HOST_IP:-}" ] || term.elog "HOST_IP has not been configured. Please update '$setup_config'"
+    [ "${HOST_NAME:-}" ] || term.elog "HOST_NAME has not been configured. Please update '$setup_config'"
+    [ "${CFG_USER:-}" ] && [ "${CFG_NAME:-}" ] && [ "${CFG_EMAIL:-}" ] && [ "${HOST_IP:-}" ] && [ "${HOST_NAME:-}" ] || trap.die 'Invalid configuration'
+
  
-
-    # verify we have the mandatory env variables defied
-    : ${HOST_IP:?"HOST_IP has not been configured. Please update '$setup_config'"}
-    : ${HOST_NAME:?"HOST_NAME has not been configured. Please update '$setup_config'"}
+    readonly CFG_USER
+    readonly CFG_NAME
+    readonly CFG_EMAIL
 
     # import our setup configuration
     lib.exportFileVars "${CONFIG_DIR}/setup.cfg" 'export'
@@ -125,20 +125,15 @@ function deploy.__initGlobals()
 # remove any running containers then delete workspace directory
 function deploy.clean()
 {
+    local network
     # check networks to determine if there are running containers
-    local network="$(basename "${WORKSPACE_DIR}")_default"
-    network="${network//./}"
-    local -i networks=$(docker network ls | grep -cs "$network")
-    if [ "$networks" -gt 0 ]; then
-        # need docker=compose.yml to stope/remove running containers
-        mkdir -p "$WORKSPACE_DIR" ||:
-        sudo cp "$CONFIG_YAML" "$WORKSPACE_YAML"
-        sudo  sed -Ei -e 's|(:\?})|:-}|g' "$WORKSPACE_YAML"
-
-        term.log 'INFO: bringing down containers to allow "workspace" to be cleaned5\n' 'lt_magenta'
-        term.log '$docker-compose down\n' 'grey'
-        docker-compose --file "$WORKSPACE_YAML" down ||:
-    fi
+    local -a networks=(  'devops-container-net'
+                         "$(basename "${WORKSPACE_DIR}")_default"
+                       )
+    for network in "${networks[@]}"; do
+        deploy.down "$network" && break
+        deploy.down "${network//./}" && break
+    done
 
     # remove workspace folder
     term.log "\$rm -rf $WORKSPACE_DIR"'\n' 'grey'
@@ -179,6 +174,28 @@ function deploy.cmdLineArgs()
 
     [ $# -eq 0 ] || term.log 'Ignoring extra arguments' 'warn'
     appenv.results
+}
+
+#----------------------------------------------------------------------------------------------
+function deploy.configSettingsHelp()
+{
+cat > /dev/stderr << EOF
+
+Please ensure that your 'git' configuration ( ~/.gitconfig) is valid. It should contain
+ 
+ [user]
+     name = Surname, Firstname
+     email = first.surname@myorg.com
+ [adsk "github"]
+     account = ntlogin
+
+You may use the following commands
+ 
+  git config --local --set user.name="Surname, Firstname"
+  git config --local --set user.email="first.surname@myorg.com"
+  git config --local --set adk.github.account="ntlogin"
+
+EOF
 }
 
 #----------------------------------------------------------------------------------------------
@@ -286,6 +303,26 @@ function deploy.createVolumeFolders()
 }
 
 #----------------------------------------------------------------------------------------------
+# down containers
+function deploy.down()
+{
+    local network="${1:?}"
+    local -i networks=$(docker network ls | grep -cs "$network")
+    [ "$networks" -gt 0 ] || return 1
+
+    # need docker-compose.yml to stop/remove running containers
+    mkdir -p "$WORKSPACE_DIR" ||:
+    sudo cp "$CONFIG_YAML" "$WORKSPACE_YAML"
+    sudo  sed -Ei -e 's|(:\?})|:-}|g' "$WORKSPACE_YAML"
+
+    term.log 'INFO: bringing down containers to allow "workspace" to be cleaned5\n' 'lt_magenta'
+    term.log '$docker-compose down\n' 'grey'
+    docker-compose --file "$WORKSPACE_YAML" down ||:
+
+    return 0
+}
+
+#----------------------------------------------------------------------------------------------
 # determine changes to line of 'docker-compose'
 # called after containers are running so that up-to-date config info is available
 function deploy.fixupDCLineAfterRun()
@@ -304,7 +341,7 @@ function deploy.fixupDCLineAfterRun()
         line="$(deploy.containerVersion "$line" "$service" | jq -r "$property")"
     fi
 
-    # update any versions.  (search for string containing  '${SOMEMODULE_VERSION:-xxxxxxxxxxxxxxx}'
+    # update any versions  (search for string containing  '${SOMEMODULE_VERSION:-xxxxxxxxxxxxxxx}'
     while read -r keyName; do
         # 'keyName' is 'SOMEMODULE_VERSION',  '!keyName' is the current/new value of 'xxxxxxxxxxxxxxx'
         line="$(sed -E 's|^(\s+.*\$\{'${keyName}':-)[^\}]+(}.*)$|\1'${!keyName}'\2|' <<< "$line")"
@@ -331,7 +368,7 @@ function deploy.fixupDCLineBeforeRun()
     # don't copy comments to output
     grep -Eq '^\s*#' <<< "$line" && return 0
 
-    # update any versions.  (search for string containing  '${SOMEMODULE_VERSION:-xxxxxxxxxxxxxxx}'
+    # update any versions  (search for string containing  '${SOMEMODULE_VERSION:-xxxxxxxxxxxxxxx}'
     while read -r keyName; do
         # 'keyName' is 'SOMEMODULE_VERSION',  '!keyName' is the current/new value of 'xxxxxxxxxxxxxxx'
         line="$(sed -E 's|^(\s+.*\$\{'${keyName}':-)[^\}]+(}.*)$|\1'${!keyName}'\2|' <<< "$line")"
